// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.CommandBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.DriveSystem;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class RotateRobotCommand extends CommandBase {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private final DriveSystem m_driveSystem;
    private double rotationSpeed;
    private double rotationRadians;
    private double encoderCountsPerRev;
    private double encoderDistancePerPulse;
    private double encoderCountsToRotate;
    private double initialEncoderPos;
    private double currentEncoderPos;
    private double rotationDegrees;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


    public RotateRobotCommand(DriveSystem subsystem, double rotationDegrees) {
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_driveSystem = subsystem;
        addRequirements(m_driveSystem);

        if (Math.signum(rotationDegrees) < 0) {
            rotationSpeed = 1.0;
        } else if (Math.signum(rotationDegrees) > 0) {
            rotationSpeed = -1.0;
        }

        this.rotationDegrees = rotationDegrees;
        rotationRadians = rotationDegrees * Math.PI / 180;
        encoderCountsPerRev = 42;
        encoderDistancePerPulse = 2.0 * Math.PI / encoderCountsPerRev;
        encoderCountsToRotate = rotationRadians / encoderDistancePerPulse * 145 / 180;
        initialEncoderPos = 0;
        m_driveSystem.getLeftFrontMotor().getEncoder().setPosition(0);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_driveSystem.getLeftFrontMotor().getEncoder().setPosition(0);
        System.out.println("RotateRobotCommand started");
        System.out.println("rotation degrees: " + rotationDegrees);
        System.out.println("initial encoder position: " + initialEncoderPos);
        System.out.println("CPR: " + encoderCountsPerRev);
        System.out.println("encoder counts to rotate: " + encoderCountsToRotate);
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        m_driveSystem.drive(0, rotationSpeed);
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_driveSystem.drive(0, 0);
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        currentEncoderPos = m_driveSystem.getLeftFrontMotor().getEncoder().getPosition();
        System.out.println("current encoder position: " + currentEncoderPos);

        if (currentEncoderPos > encoderCountsToRotate + initialEncoderPos) {
            return true;
        }

        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
